apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::911701613683:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-QuaiFCh6JaUf
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::911701613683:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::911701613683:user/ramesh
      username: ramesh 
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-28T05:27:33Z"
  name: aws-auth
  namespace: kube-system
  uid: fb964928-e4bc-40bb-a4c4-99bac12cd28c
